#!/bin/sh

bspwmInfo(){
	cur=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
	tot=$(xprop -root _NET_NUMBER_OF_DESKTOPS | awk '{print $3}')
	echo $cur
	output="^fg(white)"
	for((i=1; i<$cur; i++))
	do
		$output="$output ^rc(10x10)
}
