#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_colors

num_mon=$(bspc query -M | wc -l)

wanted_screen=$1

while read -r line ; do
	case $line in
		M*)
			#music output
			music_info="${line#?}"
			;;
		S*)
			# clock output
			sys_infos="${line#?}"
			;;
		T*)
			# xtitle output
			title="${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
 					M*)
						if [ "$name" != "$wanted_screen" ]
						then
							skip=true
						else
							skip=false
						fi
 						;;
 					m*)
						if [ "$name" != "$wanted_screen" ]
						then
							skip=true
						else
							skip=false
						fi
 						;;
					O*)
						if [ "$skip" = false ]
						then
							# focused occupied desktop
							wm_infos="${wm_infos}%{F$FG_ACTIVE} ● %{F-}"
						fi
						;;
					F*)
						if [ "$skip" = false ]
						then
							# focused free desktop
							wm_infos="${wm_infos}%{F$FG_ACTIVE} ● %{F-}"
						fi
						;;
					U*)
						if [ "$skip" = false ]
						then
							# focused urgent desktop
							wm_infos="${wm_infos}%{F$FG_ACTIVE} ● %{F-}"
						fi
						;;
					o*)
						if [ "$skip" = false ]
						then
							# occupied desktop
							wm_infos="${wm_infos} ●"
						fi
						;;
					f*)
						if [ "$skip" = false ]
						then
							# free desktop	
							wm_infos="${wm_infos} ●"
						fi
						;;
					u*)	
						if [ "$skip" = false ]
						then
							# urgent desktop
							wm_infos="${wm_infos}%{F$FG_URGENT} ● %{F-}"
						fi
						;;
# 					L*)
# 						# layout
# 						wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
# 						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${music_info}%{c}${wm_infos}%{r}${sys_infos}"
	#printf "%s\n" "%{l}${wm_infos}%{c}${title}%{r}${sys_infos}"
done
