#! /bin/bash

PANEL_HEIGHT=15
PANEL_FIFO=/tmp/panel-fifo
FONT=xft:inconsolata:size=10

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc subscribe all > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%H:%M %d-%m-%y' > "$PANEL_FIFO" &
#music > "$PANEL_FIFO" &

. panel_colors

#set the other screen that we're interested in
other=$(xrandr --query | gawk '{if (/*/) {print screen};screen=$1}' | tail -1)
# right screen
cat "$PANEL_FIFO" | panel_bar $other | lemonbar -g x15 -F "$FG" -B "$BG" -f $FONT &

sleep 1
wids=`xdo id -a bar`
`xdo lower ${wids}`

wait
