#! /bin/sh
#
# Example panel for LemonBoy's bar 
. panel_colors

num_mon=$(bspc query -M | wc -l)

big="DVI-1"
small="DVI-0"

while read -r line ; do
	case $line in
		M*)
			#music output
			music_info="${line#?}"
			;;
		S*)
			# clock output
			sys_infos="${line#?}"
			;;
		T*)
			# xtitle output
			title="${line#?}"
			;;
		W*)
			# bspwm internal state
			bigInfo=""
			smallInfo=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				case $item in
 					M*)
						name=${item#?}
						;;
 					m*)
						name=${item#?}
						;;
					O*)
						if [ "$name" == "$big" ]
						then
							# focused occupied desktop
							bigInfo="${bigInfo}%{F$FG_ACTIVE} ● %{F-}"
						else
							smallInfo="${smallInfo}%{F$FG_ACTIVE} ● %{F-}"
						fi
						;;
					F*)
						if [ "$name" == "$big" ]
						then
							# focused free desktop
							bigInfo="${bigInfo}%{F$FG_ACTIVE} ● %{F-}"
						else
							smallInfo="${smallInfo}%{F$FG_ACTIVE} ● %{F-}"
						fi
						;;
					U*)
						if [ "$name" == "$big" ]
						then
							# focused urgent desktop
							bigInfo="${bigInfo}%{F$FG_ACTIVE} ● %{F-}"
						else
							smallInfo="${smallInfo}%{F$FG_ACTIVE} ● %{F-}"
						fi
						;;
					o*)
						if [ "$name" == "$big" ]
						then
							# occupied desktop
							bigInfo="${bigInfo} ●"
						else
							smallInfo="${smallInfo} ●"
						fi
						;;
					f*)
						if [ "$name" == "$big" ]
						then
							# free desktop	
							bigInfo="${bigInfo} ●"
						else
							smallInfo="${smallInfo} ●"
						fi
						;;
					u*)	
						if [ "$name" == "$big" ]
						then
							# urgent desktop
							bigInfo="${bigInfo}%{F$FG_URGENT} ● %{F-}"
						else
							smallInfo="${smallInfo}%{F$FG_URGENT} ● %{F-}"
						fi
						;;
# 					L*)
# 						# layout
# 						wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
# 						;;
				esac
				shift
			done
			;;
	esac
	printf "%s" "%{l}${music_info}%{c}${bigInfo}%{r}${sys_infos}"
	printf "%s\n" "%{S+}%{l}${music_info}%{c}${smallInfo}%{r}${sys_infos}"
done
