#! /bin/sh

COLOR_BORDER="gray"
COLOR_FOCUSED_BORDER="black"
PANEL_SIZE=15
PADDING=10

bspc monitor DVI-0 -d I II III
bspc monitor DVI-1 -d IV V VI VII
bspc monitor HDMI-0 -d t4 t5 t6 t7

bspc config -m DVI-1 border_width	2   
bspc config -m DVI-0 border_width	2   
bspc config -m HDMI-0 border_width	2
bspc config focused_border_color $COLOR_FOCUSED_BORDER
bspc config normal_border_color $COLOR_BORDER
bspc config active_border_color $COLOR_BORDER

bspc config top_padding 		$PANEL_SIZE
bspc config -m DVI-1 window_gap $PADDING
bspc config -m DVI-0 window_gap $PADDING
bspc config -m HDMI-0 window-gap $PADDING

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     true

bspc rule --add skype desktop=V follow=off
bspc rule --add transmission desktop=VII follow=off
bspc rule --add ncmpcpp desktop=VI follow=off
bspc rule --add spotify desktop=VI follow=off sticky=on
bspc rule --add Steam desktop=III follow=off
bspc rule --add mumble desktop=V follow=off
bspc rule --add java desktop=III follow=off
bspc rule --add jetbrains-studio desktop=III follow=off
bspc rule --add jetbrains-idea desktop=III follow=off
bspc rule --add dota2 desktop=III follow=off
bspc rule --add floating_terminal state=floating
