#! /bin/sh

sxhkd &
panel &

COLOR_BORDER="#000000"
COLOR_FOCUSED_BORDER="#dd0000"
PANEL_SIZE=15
PADDING=0

bspc monitor -d I II III IV V VI

bspc config border_width	1
bspc config focused_border_color $COLOR_FOCUSED_BORDER
bspc config normal_border_color $COLOR_BORDER
bspc config active_border_color $COLOR_BORDER

bspc config top_padding $PANEL_SIZE
bspc config window_gap  $PADDING

bspc config split_ratio         0.60
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule --add java desktop=III follow=off
bspc rule --add Steam desktop=III follow=off
bspc rule --add jetbrains-studio desktop=III follow=off
bspc rule --add jetbrains-idea desktop=III follow=off
bspc rule --add dota2 desktop=III follow=off

bspc rule --add skype desktop=V follow=off
bspc rule --add mumble desktop=V follow=off
bspc rule --add "TeamSpeak 3" desktop=V follow=off

bspc rule --add ncmpcpp desktop=VI follow=off
bspc rule --add spotify desktop=VI follow=off sticky=on

bspc rule --add transmission desktop=VII follow=off

bspc rule --add floating_terminal state=floating
